# Taken liberally from https://github.com/marketplace/actions/install-nix
name: "Build with Nix"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix build
